version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: praxii-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: praxiidbuser
      MONGO_INITDB_ROOT_PASSWORD: securepassword123

