version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: praxii-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: praxii

  backend:
    build:
      context: ./backend
    container_name: praxii-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: praxii
      SERVER_PORT: 8080
    # If using Maven:
    # command: ["./mvnw", "spring-boot:run"]
    # If using pre-built jar:
    # command: ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]

  # Optionally, add the frontend later after backend/auth is complete
